# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: mikro-kit
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  EDIT.. Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "/de" # the subpath of your site, e.g. /blog
url: "https://mikro-kit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  projects:
    output: true
    # permalink: /:collection/:name

  contact:

  members:

  articles:
    output: true

  fr:
    output: true

  de:
    output: true

# Defaults
defaults:
  -
    scope:
      path: "_projects/de"
    values:
      layout: "project"
      lang: "de"

  -
    scope:
      path: "_projects/fr"
    values:
      layout: "project"
      lang: "fr"

  -
    scope:
      path: "_members/de"
    values:
      layout: "member"
      lang: "de"

  -
    scope:
      path: "_members/fr"
    values:
      layout: "member"
      lang: "fr"

  -
    scope:
      path: "_articles/de"
    values:
      layout: "article"
      lang: "de"

  -
    scope:
      path: "_articles/fr"
    values:
      layout: "article"
      lang: "fr"

  -
    scope:
      path: "_contact/de"
    values:
      layout: "default"
      lang: "de"

  -
    scope:
      path: "_contact/fr"
    values:
      layout: "default"
      lang: "fr"

github: [metadata]

plugins:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
